packages:
  core: !include sonoff-powr320d.yaml

esphome:
  project:
    name: diekruecke.sonoff-powr320d
    version: dev # This will be replaced by the github workflows with the `release` version

dashboard_import:
  package_import_url: github://diekruecke/sonoff-powr320d/sonoff-powr320d.yaml@main
  import_full_config: false

esp32_improv:
  authorizer: none
